const rentals = [
  {
    photo:
      "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_2560/s3/3/239208/belair_exterior_lores_1228.jpg",
    address: "590 Candlewyck Road, Lancaster, PA 17601",
    price: "$1,800/mo",
    bedrooms: 3,
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$30",
    petFee: "$350",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.0379,
    lon: -76.3055,
    type: "Townhouse",
    website: "https://www.belairlancaster.com",
    phoneNumber: "(717) 470-8549",
    moreDetails:
      "Part of Manheim Township School District, features finished basements, washer/dryer in each unit, and walking distance to Bucher Elementary School",
  },
  {
    photo:
      "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_2560/s3/3/239211/marfairmanor_exterior_lores_1460.jpg",
    address: "845 Pleasure Rd, Lancaster, PA 17601",
    price: "$1,343/mo",
    bedrooms: 3,
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$30",
    petFee: "$350",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.0725,
    lon: -76.3432,
    type: "Apartment",
    website: "https://www.rpmayfair.com",
    phoneNumber: "(844) 659-6858",
    moreDetails:
      "Offers upgraded kitchens/baths, adjacent to Schaeffer Elementary School, with access to off-site fitness center at Belair Townhomes",
  },
  {
    photo:
      "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_2560/s3/3/784477/lancastergreen_exterior_lores_6831.jpg",
    address: "1633 A Judie Ln, Lancaster, PA 17603",
    price: "$1,500/mo",
    bedrooms: 2,
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$35",
    petFee: "$350",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.0379,
    lon: -76.3055,
    type: "Townhouse",
    website: "https://www.rplancastergreen.com/",
    phoneNumber: "(833) 494-1284",
    moreDetails:
      "2-bedroom townhome with modern kitchen appliances including dishwasher and refrigerator. Features shared laundry facilities and plush carpeting throughout.",
  },
  {
    photo:
      "https://images1.apartments.com/i2/ZXDQr18nfCYxAaDM-CQdXZ9hImD9E0PnwuUorzgLP5Y/116/sunpointe-townhomes-harrisburg-pa-exterior-of-sunpointe-townhomes.jpg?p=1",
    address: "466 Stephen Dr, Harrisburg, PA 17111",
    price: "$1,450/mo",
    bedrooms: 2,
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$35",
    petFee: "$300",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.2732,
    lon: -76.8867,
    type: "Townhouse",
    website: "",
    phoneNumber: "(717) 695-3510",
    moreDetails:
      "Accessible townhome with washer/dryer in unit. Located near public transportation routes and features plank flooring.",
  },
  {
    photo:
      "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_2560/s3/3/611194/hamiltonpark_exterior_lores_3820.jpg",
    address: "303 Hamilton Circle, Harrisburg, PA 17111",
    price: "$1,550/mo",
    bedrooms: 2,
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$30",
    petFee: "$350",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.2732,
    lon: -76.8867,
    type: "Apartment",
    website: "",
    phoneNumber: "(717) 925-3285",
    moreDetails:
      "2-bedroom apartment with fireplace option and private balcony. Community amenities include business center and 24-hour maintenance.",
  },
  {
    photo:
      "https://images1.apartments.com/i2/B_7ZYYAv5WGicfdw6tXd-JZ3G39nDBqqDed5bbUhraM/116/rittenhouse-hill-philadelphia-pa-rittenhouse-hill-backyard.jpg?p=1",
    address: "633 W Rittenhouse St, Philadelphia, PA 19144",
    price: "$1,800/mo",
    bedrooms: 2,
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$50",
    petFee: "$300",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.0236,
    lon: -75.1933,
    type: "Apartment",
    website: "https://rittenhousehillapartments.com",
    phoneNumber: "(267) 388-4082",
    moreDetails:
      "Luxury complex with infinity edge pool, sports courts, and dog parks. Features include in-unit washer/dryer, hardwood floors, and energy-efficient appliances. Walk Score® 85 with nearby Save-A-Lot grocery store[1][5][6].",
  },
  {
    photo:
      "https://photos.zillowstatic.com/fp/04be0f61bd1954304456a44550229b97-cc_ft_768.webp",
    address: "1050 N Hancock St, Philadelphia, PA 19123",
    price: "$2,200/mo",
    bedrooms: 1,
    wheelchairAccessible: "No",
    petDeposit: "$250",
    petRent: "$50",
    petFee: "$0",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 39.9675,
    lon: -75.1392,
    type: "Apartment",
    website: "https://palazzophilly.com",
    phoneNumber: "(267) 787-6654",
    moreDetails:
      "Urban living with surface/garage parking ($195-$225/mo). Walk Score® 98 near 15+ transit routes. Features electronic thermostat, built-in storage, and 24/7 maintenance[2][6].",
  },
  {
    photo:
      "https://cdngeneral.rentcafe.com/dmslivecafe/2/46992/Amenity%20Center%20Pool%20Deck%20Overall(1).jpg?width=1024&quality=90",
    address: "101 South 39th St, Philadelphia, PA 19104",
    price: "$1,260/mo",
    bedrooms: 3,
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$50",
    petFee: "$250",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 39.9555,
    lon: -75.1996,
    type: "Student Housing",
    website: "https://hamiltoncourtphilly.com",
    phoneNumber: "(215) 839-1006",
    moreDetails:
      "UPenn-adjacent student housing (3-min walk) with 95 Walk Score®. Shared laundry facilities. Near 30th Street Station and Center City restaurants[3][7].",
  },
  {
    photo:
      "https://rentpath-res.cloudinary.com/t_w_webp_xl/t_unpaid/3f5f5c58ccab9d83427a9c493c68d58b",
    address: "1900 Chestnut St, Philadelphia, PA 19103",
    price: "$2,500/mo",
    bedrooms: 1,
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$55",
    petFee: "$350",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 39.9505,
    lon: -75.1727,
    type: "Apartment",
    website: "https://theharperphilly.com",
    phoneNumber: "(215) 568-0500",
    moreDetails:
      "Luxury high-rise with rooftop sky deck, Bark Park, and 24-hr concierge. Features Bosch appliances, granite counters, and grocery delivery services. Adjacent to Comcast Center[4][8].",
  },
  {
    photo:
      "https://photos.zillowstatic.com/fp/d01ca5fac75fc86a4cccb0bf38d691a1-cc_ft_768.webp",
    address: "1401 Spruce St, Philadelphia, PA 19102",
    price: "$3,100/mo",
    bedrooms: 2,
    wheelchairAccessible: "No",
    petDeposit: "$500",
    petRent: "$50",
    petFee: "$0",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 39.947,
    lon: -75.1636,
    type: "Apartment",
    website: "https://theatlanticbuilding.com/",
    phoneNumber: "(267) 388-2148",
    moreDetails:
      "Luxury high-rise in Avenue of the Arts South with yoga room, spa facilities, and state-of-the-art fitness center. Walk Score® 98 near 30+ restaurants and cultural venues. Features GE appliances and floor-to-ceiling windows[1][8].",
  },

  {
    photo:
      "https://images1.loopnet.com/i2/-sjK19ap2IDdTyd4u5vCPke9IgaX6cx_MIvLJuWoY3w/112/image.jpg",
    address: "35 Clinton Pl, New Rochelle, NY 10801",
    price: "Contact property",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$0",
    petFee: "$0",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.9115,
    lon: -73.7824,
    type: "Apartment",
    website: "https://sinnottmanagement.com",
    phoneNumber: "(914) 355-4555",
    moreDetails:
      "Historic Art Deco building with private beach access. Features sunken living rooms, custom woodwork, and included parking. Near Metro-North station (0.4 miles) with 35-min commute to Grand Central[2][5][9].",
  },
  {
    photo:
      "https://images1.apartments.com/i2/QusMhvAa6B0gEZPiKDYxxzu6ka8VbJ17VXoexz5uXqw/116/moda-jamaica-ny-interior-photo.jpg?p=1",
    address: "153-30 89th Ave, Jamaica, NY 11432",
    price: "$2,300/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$300",
    petRent: "$0",
    petFee: "$350",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.7056,
    lon: -73.8033,
    type: "Apartment",
    website: "https://modajamaica.com",
    phoneNumber: "(929) 552-3832",
    moreDetails:
      "346-unit luxury complex with 24hr concierge and rooftop lounge. 0.1 miles from E/J/Z trains. Features Bosch washer/dryers and quartz countertops. Near York College and Jamaica Center arts district[3][6][10].",
  },
  {
    photo:
      "https://photos.zillowstatic.com/fp/ae186ee968df353f5f7678d51d2e027a-full.webp",
    address: "152-11 89th Ave, Jamaica, NY 11432",
    price: "$2,400/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$50",
    petFee: "$0",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.7056,
    lon: -73.8031,
    type: "Apartment",
    website: "https://parkhillcity.com",
    phoneNumber: "(718) 795-4500",
    moreDetails:
      "17-story tower with JFK views (4 miles away). Features include keyless entry, children's playroom, and free shuttle to Jamaica Station. Units have GE smart thermostats and in-apartment laundry[4][7][11].",
  },
  {
    photo:
      "https://images1.apartments.com/i2/TNho8C1tOJoO6Sx7q0qGDGWR1d8uf9NoKrbaDW9YeQQ/116/node-harman-brooklyn-ny-primary-photo.jpg?p=1",
    address: "452 Harman St, Brooklyn, NY 11237",
    price: "$3,000/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$75",
    petFee: "$300",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.7027,
    lon: -73.9197,
    type: "Co-Living Space",
    website: "https://node-living.com/city/new-york/",
    phoneNumber: "",
    moreDetails:
      "no breed or weight restrictions listed, pet limit of 1, no deposit, $300 fee, pet rent of $75/month, pet interview required ",
  },
  {
    photo:
      "https://images1.apartments.com/i2/HCh8m0k9lgYaL_E25Ds13TCUT9ykYH6DjydVrPHHotk/116/harbor-1500-weehawken-nj-building-photo.jpg?p=1",
    address: "1500 Harbor Blvd, Weehawken, NJ 07086",
    price: "$3,500/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$75 per pet/month (Contact property for details)",
    petFee: "$650 per pet (Contact property for details)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.7698,
    lon: -74.0194,
    type: "Apartment",
    website: "https://www.harbor1500.com/",
    phoneNumber: "(908) 332-9311",
    moreDetails:
      "3 pet limit. No breed or weight restrictions. $650 pet fee. $75 monthly pet rent per pet.",
  },
  {
    photo:
      "https://capi.myleasestar.com/v2/dimg/66573855/1536x756/66573855.jpg",
    address: "2935 John F Kennedy Blvd, Jersey City, NJ 07306",
    price: "$3,200/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$65",
    petFee: "$500",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.7312,
    lon: -74.0651,
    type: "Apartment",
    website: "https://www.threejournalsquare.com/",
    phoneNumber: "(201) 995-6831",
    moreDetails:
      "Industrial-chic co-living space with private bedroom suites and shared kitchen/lounge areas. Features coworking spaces, bike storage, and monthly cleaning services. 0.3 miles from Jefferson St L train. Includes all utilities + weekly community dinners. Near Bushwick's art galleries and Roberta's Pizza[1][5][7].",
  },
  {
    photo:
      "https://photos.zillowstatic.com/fp/c6b8d94e302d86bb9ff59e1e8fcf0cde-uncropped_scaled_within_1536_1152.webp",
    address: "550 Washington Ave, Belleville, NJ 07109",
    price: "Contact property",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$0",
    petFee: "$0",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 40.7937,
    lon: -74.1506,
    type: "Apartment",
    website:
      "https://www.apartments.com/washington-heights-apartments-belleville-nj/bnkvh69/",
    phoneNumber: "",
    moreDetails:
      "Luxury high-rise with Manhattan skyline views from private balconies. Features include Peloton studio, resident lounge with golf simulator, and 24/7 package concierge. 0.1 miles to NY Waterway Ferry (12-min to Midtown). Smart home technology with Nest thermostats and keyless entry[3][6][8].848-214-2140",
  },
  {
    photo:
      "https://images1.apartments.com/i2/MZrztzgxHCmIypsBttVNeBb0qhnNcz2a_RbPcLraho4/116/cottage-trails-at-culpepper-landing-chesapeake-va-building-photo.jpg?p=1",
    address: "3000 Conservancy Dr, Chesapeake, VA 23323",
    price: "Contact property",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "Contact property",
    petRent: "Contact property",
    petFee: "Contact property",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 36.7631,
    lon: -76.3278,
    type: "Apartment",
    website:
      "https://www.hgliving.com/apartments/va/chesapeake/cottage-trails/?utm_knock=g",
    phoneNumber: "(757) 296-9466",
    moreDetails:
      "Pet-friendly community with 9-ft ceilings and screened patios. Features sparkling pool with sundeck, dog park, and picnic area. 0.5 miles from Chesapeake Arboretum. Includes GE appliances and hardwood-style flooring. 24-hour emergency maintenance available[1][2].",
  },
  {
    photo:
      "https://images1.apartments.com/i2/IeYUKTZwvsbVaXRaeZPVfZq_GZ0_mCczrrc_Rjv02Nk/116/maa-adalay-bay-chesapeake-va-primary-photo.jpg?p=1",
    address: "101 Sabal Palm Lane, Chesapeake, VA 23320",
    price: "$1,800/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$35 per pet/month",
    petFee: "$400 for one pet, $800 for two pets (non-refundable)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 36.7529,
    lon: -76.2376,
    type: "Apartment",
    website:
      "https://www.maac.com/virginia/chesapeake/adalay-bay/?gclid=EAIaIQobChMIk5-6jJzC5QIVkh6tBh1XXQ6OEAAYASAAEgImYvD_BwE",
    phoneNumber: "(833) 835-5619",
    moreDetails:
      "Luxury complex with free car wash station and community grills. Features sunrooms in select units, courtyard with fountain, and 24/7 maintenance. 0.3 miles from Chesapeake Regional Medical Center. Includes washer/dryer and walk-in closets[3][4][6].",
  },
  {
    photo:
      "https://images1.apartments.com/i2/UHmqsa5O9tloTJAdsJWHTqwJ4VYHrahsy1dN-Hmc8do/116/icon-norfolk-va-building-photo.jpg?p=1",
    address: "321 E Main St, Norfolk, VA 23510",
    price: "$2,100/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$30 per month per pet",
    petFee: "$400 per pet (non-refundable)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 36.8468,
    lon: -76.2908,
    type: "Apartment",
    website: "https://www.iconnorfolk.com/",
    phoneNumber: "(757) 300-0105",
    moreDetails:
      "Virginia's tallest residential skyscraper with 24th-floor rooftop lounge featuring Peloton bikes and chef kitchens. Includes free grocery delivery concierge, wine vault with tasting station, and floor-to-ceiling windows. 0.2 miles from MacArthur Center mall[5][6].",
  },
  {
    photo:
      "https://images1.apartments.com/i2/Ev3vJYc5LFT7kWPizqBAaKlBcEiTGegpInnTGxr9Ub0/116/the-alexander-at-ghent-norfolk-va-building-photo.jpg?p=1",
    address: "1600 Granby St, Norfolk, VA 23510",
    price: "$2,500/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$300 (additional $200 for second pet)",
    petRent: "$50 per month per pet",
    petFee: "$0",
    breedRestrictions: "None (Weight limit of up to 125 lbs)",
    weightRestrictions: "125 lbs max per pet",
    lat: 36.8607,
    lon: -76.2836,
    type: "Apartment",
    website: "https://www.alexander-apartments.com/",
    phoneNumber: "(757) 962-8058",
    moreDetails: "",
  },
  {
    photo:
      "https://images1.apartments.com/i2/rDnCi6QbymKXoXqNmwJfTVmXKScYBkvDW-2thpYi61U/116/the-point-on-38th-apartments-norfolk-va-building-photo.jpg?p=1",
    address: "1055 38th St, Norfolk, VA 23508",
    price: "$1,700/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$40 per month per pet",
    petFee: "$350 for first pet, $150 for second pet (non-refundable)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 36.8815,
    lon: -76.3018,
    type: "Apartment",
    website: "",
    phoneNumber: "(844) 493-9242",
    moreDetails:
      "Luxury high-rise with private Juliette balconies and floor-to-ceiling windows. Features keyless entry, in-unit washer/dryer, and electric car charging stations. 0.3 miles from Virginia Zoo. Includes 24/7 concierge and package lockers. Walk Score® 92 near 40+ restaurants[1][4]",
  },
  {
    address: "272 W Bay Ave, Norfolk, VA 23503",
    price: "$1,600/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$35 per month per pet",
    petFee: "$250 per pet (non-refundable)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 36.9487,
    lon: -76.2534,
    type: "Apartment",
    website: "https://www.thepointon38th.com/",
    phoneNumber: "(757) 904-5814",
    moreDetails: "",
  },
  {
    photo:
      "https://images1.apartments.com/i2/dRZZrMmJ227G9KejWZYie1xLTree-95j2kaFIviBrnI/116/bridgewater-at-town-center-hampton-va-building-photo.jpg?p=1",
    address: "507 Marcella Rd, Hampton, VA 23666",
    price: "$1,750/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$25 for one pet, $50 for two pets (monthly)",
    petFee: "$300 for one pet, $600 for two pets (non-refundable)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 37.048,
    lon: -76.4104,
    type: "Apartment",
    website: "https://www.bridgewaterattowncenter.com/pet-friendly",
    phoneNumber: "(757) 838-5188",
    moreDetails:
      "Modern apartments with stainless steel appliances and luxury vinyl flooring. Amenities include rooftop lounge with Manhattan views, resort-style pool, and Peloton-equipped fitness center. 9-minute walk to Old Dominion University[2][4].",
  },
  {
    photo:
      "https://images1.apartments.com/i2/GrgjYEryCP4eNZs36sybnZkAH9dSnxpsEvHkwLnLDH4/116/maa-township-hampton-va-primary-photo.jpg?p=1",
    address: "260 Marcella Rd, Hampton, VA 23666",
    price: "$1,800/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$50 per month per pet",
    petFee: "$500 per pet (non-refundable)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: 37.0485,
    lon: -76.4109,
    type: "Apartment",
    website: "https://www.townshiphamptonwoods.com/",
    phoneNumber: "(833) 268-1186",
    moreDetails:
      "Accessible units with smart home technology and pre-installed WiFi. Features dog wash station, secured parking garage ($50/month), and EV charging. 0.4 miles from Norfolk Botanical Garden[2][4]",
  },
  {
    photo:
      "https://images1.apartments.com/i2/2PNJDK11uiFwJ1wwPMkBsPNsP634bW3XECbbwLynJ04/116/south-beach-apartments-virginia-beach-va-pool.jpg?p=1",
    address: "400 Eden Roc Cir, Virginia Beach, VA",
    price: "$2,200/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$0",
    petRent: "$35 per month per pet ($15 additional rent for more pets)",
    petFee: "$400 per pet ($200 additional fee for more pets)",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: "36.8427",
    lon: "-75.9792",
    type: "Apartment",
    website: "https://www.southbeachvb.com/",
    phoneNumber: "(757)437-0001",
    moreDetails:
      "Lakefront community with two resort-style saltwater pools and nature trails. Features Nest thermostats, granite countertops, and private garages. 5-minute drive to Peninsula Town Center shopping. Includes free coffee bar and sauna[3][5].",
  },
  {
    photo:
      "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_2560/s3/3/511786/fl_pensacola_emberridge_p0521435_3_03_1_photogallery.jpg",
    address: "4710 Prieto Drive, Pensacola, FL 32506",
    price: "$2,200/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$0",
    petFee: "$300",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: "30.408016",
    lon: "-87.280205",
    type: "Apartment",
    website: "https://www.emberridgeapts.com/",
    phoneNumber: "(757)437-0001",
    moreDetails:
      " One-Time, Non-Refundable Fee: $300.00 per pet No breed restrictions! You are allowed up to 2 pets. 2 dogs or 2 cats, or one of each. ",
  },
  {
    photo:
      "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/5319/pool%202(2).jpg",
    address: "6601 W Plano Pky, Plano, TX 75093",
    price: "$2,200/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$0",
    petFee: "$500",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: "33.033215",
    lon: "-96.842684",
    type: "Apartment",
    website: "https://www.prestonwoodhillsapts.com/",
    phoneNumber: "(469) 388-0769",
    moreDetails:
      " 2 pets max. No pet fee or monthly pet rent. $500 deposit per pet. Both dogs and cats are welcome. You are allowed up to two dogs or two cats or one of each. Restrictions: No breed restrictions  ",
  },
  {
    photo:
      "https://images1.apartments.com/i2/7IO9hsU5dEWF0BC2jggI16i5A53E9YXhe2TUOCHFyuA/116/parkview-towers-englewood-co-primary-photo.jpg?p=1",
    address: "3650 S Pennsylvania Street, Englewood, CO 80113",
    price: "$1,295 - $1,900/mo",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$500",
    petRent: "$35",
    petFee: "$250",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: "39.650128",
    lon: "-104.981502",
    type: "Apartment",
    website: "http://parkviewtowersdenver.com/",
    phoneNumber: "720-644-6372",
    moreDetails:
      "no weight or breed restrictions. vaccinations needed. pet fee of $250 per pet and monthly pet rent of $35/month/pet. deposit from $500-$1000 ",
  },
  {
    photo:
      "https://images1.apartments.com/i2/_Z70ggvC7kSjWMEF0L3W8Q-WKpDxDkAQdp1MY5cICW8/116/carson-catalina-apartments-carson-city-nv-rental-center-with-new-landscaping-and-w.jpg?p=1",
    address: "700 Hot Springs Rd, Carson City, NV 89706",
    price: "$1,595 – $2,139",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$300",
    petRent: "$0",
    petFee: "$0",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: "39.188153",
    lon: "-119.762364",
    type: "Apartment",
    website: "https://www.prestonwoodhillsapts.com/",
    phoneNumber: "(844) 226-5916",
    moreDetails:
      "3 pet limit, one time pet deposit $300 per pet. one time dna sample (dogs only) $75. 3 dog parks, dog washing station, zero pet rent ",
  },
  {
    photo:
      "https://images1.apartments.com/i2/sAPsSkTdc8DeoD_4rZK4R36COfRuL8DA2MpokPpkh5U/116/paramount-place-aberdeen-sd-primary-photo.jpg?p=1",
    address: "2802 3rd Ave SE, Aberdeen, SD 57401",
    price: "$1,595 – $2,139",
    bedrooms: "Contact property",
    wheelchairAccessible: "Yes",
    petDeposit: "$500",
    petRent: "$0",
    petFee: "$100",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: "45.462052",
    lon: "-98.449262",
    type: "Apartment",
    website:
      "https://www.valleyrental.net/apartments/aberdeen-sd/paramount-place-apartments/",
    phoneNumber: "605-229-8632",
    moreDetails:
      "3 pet limit, one time pet deposit $300 per pet. one time dna sample (dogs only) $75. 3 dog parks, dog washing station, zero pet rent ",
  },
  {
    photo:
      "https://images1.apartments.com/i2/20SA3aoFAJM3Em2HCryqWDfzNR-YebsYmXh73CseUds/116/kitterman-woods-port-saint-lucie-fl-primary-photo.jpg?p=1",
    address: "6600 Woods Island Cir, Port St. Lucie, FL 34952",
    price: "$1,741 – $2,460",
    bedrooms: "Contact property",
    wheelchairAccessible: "No",
    petDeposit: "$0",
    petRent: "$25",
    petFee: "$400",
    breedRestrictions: "None",
    weightRestrictions: "None",
    lat: "27.344141",
    lon: "-80.320355",
    type: "Apartment",
    website: "https://kittermanwoods.com/",
    phoneNumber: "(772) 261-9954",
    moreDetails:
      "3 pet limit, one time pet deposit $300 per pet. one time dna sample (dogs only) $75. 3 dog parks, dog washing station, zero pet rent ",
  },
  {
    photo:
      "https://photos.zillowstatic.com/fp/a0250b7c4a10e53c979720295f8ab3c4-cc_ft_768.webp",
    address: "397 Arbor Way, Auburn, AL 368302",
    price: "$3,600",
    bedrooms: "4",
    wheelchairAccessible: "No",
    petDeposit: "$350",
    petRent: "$25",
    petFee: "$400",
    breedRestrictions: "Yes",
    weightRestrictions: "Yes",
    lat: "32.615695",
    lon: "-85.488779",
    type: "House",
    website: "https://www.hayleymanagement.com/",
    phoneNumber: "(334) 947-1337",
    moreDetails:
      "This 4 bed/3.5 bath, two-story home, with a massive open floor plan, sits quietly in the coziest neighborhood that will make your 5 minute walk to campus a breath of fresh air. You will fall in love with the landscaping, private drive and storing your vehicles in the luxurious two car garage. ",
  },
  {
    photo:
      "https://images.after55.com/i2/ABETE63o-6iNcQGXd1vrMRxRBF6tMEkEj_NHfSa_uSI/112/image.jpg?p=1",
    address: "3555 SW Copper Ave, Grandville, MI 49418",
    price: "",
    bedrooms: "4",
    wheelchairAccessible: "Yes",
    petDeposit: "",
    petRent: "",
    petFee: "",
    breedRestrictions: "No pets allowed",
    weightRestrictions: "No pets allowed",
    lat: "42.873398",
    lon: "-85.752057",
    type: "Senior Housing",
    website:
      "https://www.after55.com/mi/grandville/rivertown-ridge-senior-living/bfdb0j8",
    phoneNumber: "(616) 258-2727",
    moreDetails:
      "This property is intended and operated in accordance with the Housing for Older Persons provisions of the Fair Housing Act.",
  },
];

export default rentals;
